name: Run tests

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - develop

  pull_request:

  workflow_dispatch:
    inputs:
      node-version:
        type: string
        required: false

jobs:
  tests:
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-24.04' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version || vars.NODE_VERSION || 'v22.14.0' }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test
